// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostalService.DataBase;

#nullable disable

namespace PostalService.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20240320204423_MigrationV5")]
    partial class MigrationV5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostalService.Models.UniqueId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("UintId")
                        .HasColumnType("bigint");

                    b.Property<long>("UintValidity")
                        .HasColumnType("bigint");

                    b.Property<int>("WritingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WritingId")
                        .IsUnique();

                    b.ToTable("UniqueId");
                });

            modelBuilder.Entity("PostalService.Models.Writing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tityle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("СompanyMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("СompanyMemberId");

                    b.ToTable("Writings");
                });

            modelBuilder.Entity("PostalService.Models.СompanyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IncomingIMAP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("PostalService.Models.UniqueId", b =>
                {
                    b.HasOne("PostalService.Models.Writing", null)
                        .WithOne("MailId")
                        .HasForeignKey("PostalService.Models.UniqueId", "WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostalService.Models.Writing", b =>
                {
                    b.HasOne("PostalService.Models.СompanyMember", null)
                        .WithMany("ListWriting")
                        .HasForeignKey("СompanyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostalService.Models.Writing", b =>
                {
                    b.Navigation("MailId")
                        .IsRequired();
                });

            modelBuilder.Entity("PostalService.Models.СompanyMember", b =>
                {
                    b.Navigation("ListWriting");
                });
#pragma warning restore 612, 618
        }
    }
}
